workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.11.9

stages:
  - test
  - deploy

before_script:
  - pip install -r backend/requirements.txt
  - pip install wemake-python-styleguide

flake8:
  stage: test
  script:
    - flake8 backend/api

