networks:
  app-network:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  backend:
    build: backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DB_USER: sashapenkin12
      DB_PASSWORD: sanek529
      DB_HOST: db:5432
      DB_NAME: database


  frontend:
    build: frontend
    container_name: frontend
    restart: always
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: sashapenkin12
      POSTGRES_PASSWORD: sanek529
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:
